### ISSUE TITLE
Npm is not defined

### ISSUE THREAD

**Issue by p-j** [iDoRecall/email-normalize#1]
Hi there,

As stated in an issue reported today on [`jparker:gravatar`](https://github.com/p-j/meteor-gravatar/issues/5) it seems you need to add something like

```
Npm.depends({"dns": "0.2.2"})
```

To your `package.js`

**Comment by dandv** [comment]
I'm afraid that DNS module is not it. We use [the core DNS module from node](https://nodejs.org/api/dns.html) - see https://github.com/iDoRecall/email-normalize/blob/master/email.js#L3. Can you reproduce the error?

**Comment by p-j** [comment]
Ok, so that may not be the solution, but `Npm` is still not defined and the stack trace is pointing to that [`Npm.require('dns')`](https://github.com/iDoRecall/email-normalize/blob/master/email.js#L3), don't you need to do something to get `Npm` in the global namespace ?
I haven't done much meteor development lately some I'm just guessing a that point.

**Comment by dandv** [comment]
Maybe in some old version of Meteor, but I doubt it.

The fact that `jparker:gravatar` [tests](https://github.com/p-j/meteor-gravatar/blob/master/tests/tests.js#L59) pass proves that the problem is triggered by something in @kristijanhusak's code.

**Comment by p-j** [comment]
Unfortunately, the error is also in the [test result](https://travis-ci.org/p-j/meteor-gravatar#L181) it just doesn't break the test because I'm not using the DNS part of the package.

Could it be me requesting it to work also [client side](https://github.com/p-j/meteor-gravatar/blob/master/package.js#L15) that makes it throw that error ?
In that case I'm not sure how to implement `email-normalize` if its not going to work both serverside and clientside.

**Comment by kristijanhusak** [comment]
@dandv I have the latest version of Meteor (1.1.0.3). In older gravatar version everything works fine, so it's not my code, and trace leads to that line in email normalize. Isn't there another way to require dns?

**Comment by p-j** [comment]
Actually based on the result of the tests it is clear that the issue is the package running on the client side.
Only the server tests are passing. Strange that TravisCI still says that the build is ok though.

**Comment by kristijanhusak** [comment]
https://github.com/meteorhacks/npm/issues/83

**Comment by dandv** [comment]
Ah, yes, dns isn't available client side - https://github.com/iDoRecall/email-normalize/blob/master/email.js#L5

**Comment by dandv** [comment]
Ah, yes, dns isn't available client side - https://github.com/iDoRecall/email-normalize/blob/master/email.js#L5

I'll fix the code to use that 3rd party DNS service on the client, but what's weirder is that `meteor test-packages ./` only shows `S` instead of both server and client.

**Comment by p-j** [comment]
It crashes because of the undefined reference, so the tests are never run.
What is weird to me is that crashing seems an ok outcome for the test tool...

**Comment by dandv** [comment]
The last commit adds client-side support. Please file new issues if any problems occur, and thanks for using the package!

**Comment by p-j** [comment]
Can you publish 1.0 to atmosphere ?

**Comment by dandv** [comment]
[Done](https://atmospherejs.com/idorecall/email-normalize).
